### ISSUE TITLE
`fixer-return` should (optionally?) only require it __sometimes__ returns a value

### ISSUE THREAD

**Issue by edg2s** [not-an-aardvark/eslint-plugin-eslint-plugin#102]
The rule guards against people forgetting to return their fixers, e.g.
```js
// Invalid
fix: function( fixer ) {
  fixer.replaceText( node, 'foo' );
}
```

However it is common that a fixer can only fix a subset of cases, and so only conditionally returns:
```js
// Valid
fix: function( fixer ) {
  if ( node.arguments.length ) {
    return fixer.replaceText( node, 'foo' );
  }
}
```

It should be possible to consider the above valid, while also warning about the first example.

**Comment by bradzacher** [comment]
you should really `return null` in those cases.

Implicitly returning `undefined` is a bad coding practice.

**Comment by edg2s** [comment]
Surely it should be up to `consistent-return` to decide that?

**Comment by bradzacher** [comment]
I'm strongly against that code style as I think it's a real source of bugs and potential problems.
I don't think this a good inclusion in the rule as it can be very easy for people to forget to return things, esp with the complex branching and conditional logic fixers can have.

```js
fix(fixer) {
  const fixes = [];
  fixes.push(doFix1();
  // ...

  if (someCond) {
    fixes.push(doFixN());
    return fixes;
  }

  // oops forgot to return fixes, now the code that didn't satisfy someCond didn't get a fix!
}
```

**Comment by edg2s** [comment]
My point is that you can enforce your preference with `consistent-return`. For those who prefer not to turn on `consistent-return` this rule overrides their preference.

**Comment by edg2s** [comment]
This rule has a type of `problem` and we only know there is a problem if the code _never_ returns. Anything else is a code-style suggestion and therefore better handled by another rule (`consistent-return` is type `suggestion`).

**Comment by bradzacher** [comment]
my point is that this rule is about ensuring that you return the fixer object so that eslint provide the fix.
it should work independent of `consistent-return`.

in your specific example, the fixer is a small, simple case and it's easy to see that the fixer is correct.
However there are many fixer that are not that simple, and this rule needs to handle all cases appropriately. IMO it is better to err on the safer side to help catch accidentally broken fixers.

If you want to have a simple fixer like your example, you could also just omit the fix function for your case:
```js
context.report({
  ...stuff,
  fix: !node.arguments.length
    ? null
    : function( fixer ) {
      return fixer.replaceText( node, 'foo' );
    },
});
```

This code is much clearer - it very clearly communicates the intention that you do not want any fixes if the length is falsy.

**Comment by aladdin-add** [comment]
closing as fixed.
